version: "3.7"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "ecom"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
