package main

import (
	"fmt"
	"log"
	"os"

	"github.com/rsbh/ecom/config"
	"github.com/rsbh/ecom/database"
	"gorm.io/gorm"

	"github.com/gin-gonic/gin"

	"github.com/rsbh/ecom/api"
	_ "github.com/rsbh/ecom/docs" // docs is generated by Swag CLI, you have to import it.

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title ecom API
// @version 1.0
func InitRouter(logger *log.Logger, db *gorm.DB) *gin.Engine {
	r := gin.Default()
	h := api.NewHandler(logger, db)
	apiRouter := r.Group("/api")
	h.SetupRoutes(apiRouter)
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	return r
}

func main() {
	logger := log.New(os.Stdout, "", log.LstdFlags)
	c := config.LoadConfig(logger)
	db := database.Connect(c.Database)
	database.AutoMigrate(db)
	r := InitRouter(logger, db)
	logger.Fatal(r.Run(fmt.Sprintf("%s:%d", c.Server.Address, c.Server.Port)))
}
