package router

import (
	"github.com/gin-gonic/gin"

	_ "github.com/rsbh/ecom/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/rsbh/ecom/router/api"

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title ecom API
// @version 1.0
func InitRouter() *gin.Engine {
	r := gin.Default()

	apiRouter := r.Group("/api")
	apiRouter.GET("/ping", api.Ping)

	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	return r
}
