package router

import (
	"log"

	"github.com/gin-gonic/gin"

	"github.com/rsbh/ecom/api"
	_ "github.com/rsbh/ecom/docs" // docs is generated by Swag CLI, you have to import it.

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title ecom API
// @version 1.0
func InitRouter(logger *log.Logger) *gin.Engine {
	r := gin.Default()
	h := api.NewHandler(logger)
	apiRouter := r.Group("/api")
	apiRouter.GET("/ping", h.Ping)

	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	return r
}
